export * from './capitalize'
export * from './plural'
export * from './repeat'
export * from './split'
export * from './substr'
export * from './substring'
export * from './toLowerCase'
export * from './toUpperCase'
export * from './trim'

export { toString } from '@typed/common'
